[package]
name = "oxideterm-x11-forwarding"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
rand.workspace = true
serde.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
zeroize.workspace = true
tempfile = "3.23"

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Foundation", "Win32_System_JobObjects", "Win32_System_Threading"] }
